//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoursePlatform.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CoursePlatformEntities : DbContext
    {
        public CoursePlatformEntities()
            : base("name=CoursePlatformEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CP_Course> CP_Course { get; set; }
        public virtual DbSet<CP_Duration> CP_Duration { get; set; }
        public virtual DbSet<CP_Gender> CP_Gender { get; set; }
        public virtual DbSet<CP_RegisteredCourse> CP_RegisteredCourse { get; set; }
        public virtual DbSet<CP_Registration> CP_Registration { get; set; }
        public virtual DbSet<CP_Result> CP_Result { get; set; }
        public virtual DbSet<CP_Student> CP_Student { get; set; }
        public virtual DbSet<CP_User> CP_User { get; set; }
    }
}
