//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoursePlatform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CP_Course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CP_Course()
        {
            this.CP_Duration = new HashSet<CP_Duration>();
            this.CP_RegisteredCourse = new HashSet<CP_RegisteredCourse>();
            this.CP_User2 = new HashSet<CP_User>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int Gender { get; set; }
        public string Details { get; set; }
        public string Image { get; set; }
        public int CreatorID { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<int> ModifiedID { get; set; }
        public Nullable<System.DateTime> ModficationDate { get; set; }
    
        public virtual CP_Gender CP_Gender { get; set; }
        public virtual CP_User CP_User { get; set; }
        public virtual CP_User CP_User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CP_Duration> CP_Duration { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CP_RegisteredCourse> CP_RegisteredCourse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CP_User> CP_User2 { get; set; }
    }
}
