//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoursePlatform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CP_RegisteredCourse
    {
        public int RegisteredID { get; set; }
        public int CourseID { get; set; }
        public int DurationID { get; set; }
        public Nullable<int> ResultID { get; set; }
        public Nullable<int> SerialNumber { get; set; }
    
        public virtual CP_Course CP_Course { get; set; }
        public virtual CP_Duration CP_Duration { get; set; }
        public virtual CP_Registration CP_Registration { get; set; }
        public virtual CP_Result CP_Result { get; set; }
    }
}
