//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoursePlatform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CP_Student
    {
        public string StudentCode { get; set; }
        public string StudentName { get; set; }
        public string StudentFaculty { get; set; }
    }
}
